---
sidebar: sidebar 
permalink: install-setup/initialize-ontap-cluster.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30 initialize cluster, set up cluster, ontap 
summary: 了解如何使用System Manager在ASA R2系统上设置ONTAP集群。 
searchtitle: 使用ONTAP系统管理器| ASA R2设置ONTAP集群 
---
= 在ASA R2存储系统上设置ONTAP集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP系统管理器可指导您快速轻松地完成ONTAP ASA R2集群设置工作流。

在集群设置期间、系统会创建默认数据Storage Virtual Machine (VM)。您也可以选择启用域名系统(DNS)来解析主机名、将集群设置为使用网络时间协议(NTP)进行时间同步、以及启用空闲数据加密。

.开始之前
收集以下信息：

* 集群管理 IP 地址
+
集群管理IP地址是集群管理接口的唯一IPv4地址、集群管理员可使用此地址访问管理Storage VM和管理集群。您可以从组织中负责分配 IP 地址的管理员处获取此 IP 地址。

* 网络子网掩码
+
在集群设置期间、ONTAP建议使用一组适合您的配置的网络接口。如有必要、您可以调整此建议。

* 网络网关IP地址
* 配对节点IP地址
* DNS域名
* DNS名称服务器IP地址
* NTP服务器IP地址
* 数据子网掩码


.步骤
. 发现集群网络
+
.. 将笔记本电脑连接到管理交换机并访问网络计算机和设备。
.. Open File Explorer.
.. 选择*网络*；然后右键单击并选择*刷新*。
.. 选择ONTAP图标；然后接受屏幕上显示的任何证书。
+
System Manager opens.



. 在*Password*下，为管理员帐户创建一个强密码。
+
密码长度必须至少为八个字符、并且必须至少包含一个字母和一个数字。

. 重新输入密码进行确认，然后选择*继续*。
. 在*网络地址*下，输入存储系统名称或接受默认名称。
+
如果更改了默认存储系统名称、则新名称必须以字母开头、并且必须少于44个字符。您可以在名称中使用句点(.)、连字符(-)或下划线(_)。

. 输入配对节点的集群管理IP地址、子网掩码、网关IP地址和IP地址；然后选择*继续*。
. 在*网络服务*下，选择所需选项*使用域名系统(DNS)解析主机名*和*使用网络时间协议(NTP)保持时间同步*。
+
如果选择使用DNS、请输入DNS域和名称服务器。如果选择使用NTP，请输入NTP服务器，然后选择*CONTINE*。

. 在*加密*下、输入板载密钥管理器(OKM)的密码短语。
+
默认情况下、使用板载密钥管理器(Onboard Key Manager、OKM)加密空闲数据处于选中状态。如果要使用外部密钥管理器、请更新所选内容。

+
或者、您也可以在集群设置完成后配置集群进行加密。

. 选择*初始化*。
+
设置完成后、系统会将您重定向到集群的管理IP地址。

. 在*网络*下，选择*配置协议*。
+
[cols="2"]
|===
| 要配置IP (iSCSI和NVMe/TCP)、请执行以下操作... | 要配置FC和NVMe/FC、请执行以下操作... 


 a| 
.. 选择*IP*；然后选择*Configure IP interfaces*。
.. 选择*添加子网*。
.. 输入子网的名称、然后输入子网IP地址。
.. 输入子网掩码，并可选择输入网关，然后选择*Add*。
.. 选择刚刚创建的子网，然后选择*Save*。
.. 选择 * 保存 * 。

 a| 
.. 选择*FC*；然后选择*配置FC接口*和/或*配置NVMe/FC接口*。
.. 选择FC和/或NVMe/FC端口；然后选择*保存*。


|===
. (可选)下载并运行link:https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["ActiveIQ Config Advisor"]以确认您的配置。
+
ActiveIQ Config Advisor是一款适用于NetApp系统的工具、用于检查常见配置错误。



.下一步是什么？
您已准备好link:set-up-data-access.html["设置数据访问"]从SAN客户端到ASA R2系统。
