---
sidebar: sidebar 
permalink: install-setup/install-setup-requirements.html 
keywords: asa r2, install, setup, requirements, cautions 
summary: 查看ASA R2存储系统和存储架所需的设备以及吊装预防措施。 
---
= ASA R2存储系统的安装要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
查看ASA R2存储系统和存储架所需的设备以及吊装预防措施。



== 安装所需的设备

要安装ASA R2存储系统、您需要以下设备和工具。

* 访问Web浏览器以配置存储系统
* 静电放电(ESD)带
* Flashlight
* 具有USB/串行连接的笔记本电脑或控制台
* 回形针或窄尖头圆珠笔、用于设置存储架ID
* Phillips #2 screwdriver




== 提升注意事项

ASA R2存储系统和存储架很重。搬运这些物品时请务必小心。



=== 存储系统重量

移动或抬起ASA R2存储系统时、请采取必要的预防措施。

[role="tabbed-block"]
====
.A1K
--
ASA A1K存储系统的重量可达22.83磅(28.5千克)。要抬起存储系统、请两个人或使用液压升降机。

image::../media/drw_a1k_weight_caution_ieops-1698.svg[ASA A1K提升注意图标]

--
.A70和A90
--
ASA A70或ASA A90存储系统的最大重量为68.8千克(151.68磅)。要抬起存储系统、请使用四个人或一台液压升降机。

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[ASA A90]

--
.-20、A30和A50
--
ASA A20、ASA A30或ASA A50存储系统的最大重量为27.9千克(61.5磅)。要抬起存储系统、请两个人或使用液压升降机。

image::../media/drw_g_lifting_weight_ieops-1831.svg[ASA A20,A30,or an A50 weight caution icon]

--
====


=== 存储架重量

移动或抬起磁盘架时、请采取必要的预防措施。

[role="tabbed-block"]
====
.NS224磁盘架
--
NS224磁盘架的重量不超过66.78磅(30.29千克)。要抬起磁盘架、请两个人或使用液压升降机。将所有组件(前部和后部)保留在磁盘架中、以防止磁盘架重量不平衡。

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 NSM100提升注意事项]

--
.具有NSM100B模块的NS224磁盘架
--
带有NSM100B模块的NS224磁盘架的重量可达56.8磅(25.8千克)。要抬起磁盘架、请两个人或使用液压升降机。将所有组件(前部和后部)保留在磁盘架中、以防止磁盘架重量不平衡。

image::../media/drw_ns224_nsm100b_lifting_weight_ieops-1832.svg[NS224和NSM100b提升注意事项]

--
====
.相关信息
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["安全信息和法规声明"^]


.下一步是什么？
查看硬件要求后，您可以link:prepare-hardware.html["准备安装ASA R2存储系统"]：
