---
sidebar: sidebar 
permalink: install-setup/set-up-data-access.html 
keywords:  
summary:  
---
= 启用从SAN主机到ASA R2存储系统的数据访问
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要设置数据访问、您应确保已正确配置SAN客户端上的关键参数和设置、以便在ONTAP中正常运行。如果要为VMware环境提供存储、则应安装OTV 10.3、以便轻松管理ASA R2存储。



== 设置从SAN主机的数据访问

根据主机操作系统和协议的不同、设置SAN主机对ASA R2系统的数据访问所需的配置也会有所不同。正确的配置对于获得最佳性能和成功进行故障转移至关重要。

link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["VMware vSphere SCSI客户端"^]link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["VMware vSphere NVMe客户端"^]link:https://docs.netapp.com/us-en/ontap-sanhost/overview.html["其他SAN客户端"^]要正确配置主机以连接到ASA R2系统，请参见和的ONTAP SAN主机文档。



== 迁移VMware虚拟机

如果您需要将VM工作负载从ASA存储系统迁移到ASA R2存储系统、NetApp建议您使用link:https://www.vmware.com/products/cloud-infrastructure/vsphere/vmotion["VMware vSphere vMotion"^]对数据执行实时、无中断迁移。



== 在VMware环境中将ASA R2系统配置为存储提供程序

您可以使用适用于VMware的ONTAP工具在VMware环境中轻松启用ASA R2系统作为存储提供程序。

适用于VMware vSphere的ONTAP工具是一组可与VMware vCenter Server虚拟设备(vCSA)结合使用的工具、用于轻松管理VMware ESXi主机上的虚拟机。

及更高版本支持ASA R2系统link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/concepts/ontap-tools-overview.html["适用于 VMware vSphere 的 ONTAP 工具 10.3"]。

了解如何操作link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["部署适用于VMware的ONTAP工具"^]、然后使用它执行以下操作：

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["添加vCenter Server实例"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-esx-server-multipath-and-timeout-settings.html["配置ESXi主机设置"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/discover-storage-systems-and-hosts.html["发现ASA R2存储系统和主机"^]


.下一步是什么？
您已准备好link:../manage-data/provision-san-storage.html["配置存储"]使SAN主机能够向存储单元读写数据。
