---
sidebar: sidebar 
permalink: install-setup/set-up-data-access.html 
keywords:  
summary:  
---
= 启用从SAN主机到ASA R2存储系统的数据访问
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要设置数据访问、您应确保已正确配置SAN客户端上的关键参数和设置、以便在ONTAP中正常运行。如果要为VMware环境提供存储、则应安装OTV 10.3、以便轻松管理ASA R2存储。



== 设置从SAN主机的数据访问

根据主机操作系统和协议的不同、设置SAN主机对ASA R2系统的数据访问所需的配置也会有所不同。正确的配置对于获得最佳性能和成功进行故障转移至关重要。

link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["VMware vSphere SCSI客户端"^]link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["VMware vSphere NVMe客户端"^]link:https://docs.netapp.com/us-en/ontap-sanhost/overview.html["其他SAN客户端"^]要正确配置主机以连接到ASA R2系统，请参见和的ONTAP SAN主机文档。



== 迁移VMware虚拟机

如果您需要将虚拟机工作负载从ASA存储系统迁移到ASA r2 存储系统， NetApp建议您使用link:https://www.vmware.com/products/cloud-infrastructure/vsphere-foundation["VMware vSphere vMotion"^]执行实时、无中断的数据迁移。

.相关信息
* 详细了解link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vsphere-why.html["使用ONTAP for vSphere 的优势"^] 。
* 了解link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-srm-overview.html["使用ONTAP 的VMware Live Site Recovery"^]。
* 了解link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware_vmsc_overview.html#continuous-availability-solutions-for-vsphere-environments["适用于 vSphere 环境的持续可用性解决方案"^]。




== 从第三方存储系统迁移数据

从ONTAP 9.17.1 开始，您可以使用外部 LUN 导入 (FLI) 将数据从第三方存储系统上的 LUN 迁移到ASA r2 系统。使用 FLI 进行数据迁移可以帮助您降低迁移过程中数据丢失和停机的风险。

FLI 支持在线和离线迁移。在在线迁移中，客户端系统保持在线，同时将数据从第三方存储系统复制到ONTAP存储系统。Windows、Linux 和 ESXi 主机操作系统支持在线迁移。在离线迁移中，客户端系统处于离线状态，LUN 数据从第三方存储系统复制到ONTAP存储系统，然后客户端系统重新处于在线状态。

* 学习如何执行link:https://docs.netapp.com/us-en/ontap-fli/san-migration//concept_fli_offline_workflow.html["FLI 离线迁移"^] 。
* 学习如何执行link:https://docs.netapp.com/us-en/ontap-fli/san-migration//concept_fli_online_workflow.html["FLI 在线迁移"^] 。




== 在VMware环境中将ASA R2系统配置为存储提供程序

您可以使用适用于VMware的ONTAP工具在VMware环境中轻松启用ASA R2系统作为存储提供程序。

适用于VMware vSphere的ONTAP工具是一组可与VMware vCenter Server虚拟设备(vCSA)结合使用的工具、用于轻松管理VMware ESXi主机上的虚拟机。

及更高版本支持ASA R2系统link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/concepts/ontap-tools-overview.html["适用于 VMware vSphere 的 ONTAP 工具 10.3"^]。

了解如何操作link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["部署适用于VMware的ONTAP工具"^]、然后使用它执行以下操作：

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["添加vCenter Server实例"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-esx-server-multipath-and-timeout-settings.html["配置ESXi主机设置"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/discover-storage-systems-and-hosts.html["发现ASA R2存储系统和主机"^]


.下一步是什么？
您已准备好link:../manage-data/provision-san-storage.html["配置存储"]使SAN主机能够向存储单元读写数据。
