---
sidebar: sidebar 
permalink: secure-data/respond-anti-ransomware-protection-alerts.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, ai, alerts, respond, warnings, security 
summary: 查看潜在勒索软件攻击的警告并在系统管理器中采取行动。 
---
= 响应 ASA r2 存储系统上的 ARP/AI 警报
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果 Autonomous Ransomware Protection with Artificial Intelligence (ARP/AI) 在 ASA r2 系统上的一个或多个存储单元上检测到异常活动，System Manager 会在仪表板上显示警告。查看警告，验证活动，并在必要时采取措施保护您的数据。

如果显示 ARP/AI 警告消息，请在执行操作之前使用相应的应用程序完整性检查器验证存储单元上的数据。验证存储单元的数据完整性有助于您确定该活动是否可接受，或是否为潜在的勒索软件攻击。

[cols="2,2"]
|===
| 如果出现异常活动... | 操作 


| 可接受 | 将该活动标记为误报。 


| 潜在的勒索软件攻击 | 将该活动标记为潜在的勒索软件攻击。 


| 不确定 | 不要立即采取行动。监控存储单元长达 7 天。如果存储单元继续正常运行，请将活动标记为误报。如果存储单元继续显示异常活动，请将该活动标记为潜在的勒索软件攻击。 
|===
.步骤
. 在 System Manager 中，选择 * 信息板 * 。
+
如果 ARP/AI 在一个或多个存储单元上检测到异常活动，则会在*警告*下显示一条消息。

. 选择警告消息。
. 在“事件概览”下，选择指示具有异常活动的存储单元数量的“警告”消息。
. 在*具有异常活动的存储单元*下，选择存储单元。
. 选择*安全*。
+
如果存储单元上存在异常活动，则会在“反勒索软件”下显示一条消息。

. 选择*选择一个操作*。
. 选择*标记为误报*或选择*标记为潜在勒索软件攻击*。


.下一步是什么？
如果您知道存储单元活动出现浪涌，无论是一次性浪涌还是具有新常态特征的浪涌，您都应将其报告为安全。手动将这些浪涌报告为安全有助于提高 ARP 威胁评估的准确性。了解如何 link:https://docs.netapp.com/us-en/ontap/anti-ransomware/manage-parameters-task.html#report-known-surges["报告已知的 ARP/AI 浪涌"^]。
