---
sidebar: sidebar 
permalink: learn-more/additional-supported-ontap-features.html 
keywords: asa r2, asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, cli, command line interface, clustered external key servers, external key management, encryption at rest, administrator access management, client authentication, oauth 2.0, saml authentication, fips compliance, link aggregation groups, iscsi, fibre channel, fc, nvme, nvme unmap, hole punch, deallocation, system manager 
summary: 由于ASA r2 系统运行的是ONTAP的精简版本，因此许多常见的ONTAP任务和系统管理器功能在ASA r2 系统上的执行方式与在其他ONTAP系统上的执行方式相同。 
---
= ASA r2 系统支持的常见ONTAP功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
由于ASA r2 系统运行的是ONTAP的精简版本，因此许多常见的ONTAP任务和系统管理器功能在ASA r2 系统上的执行方式与在其他ONTAP系统上的执行方式相同。

有关常见特性和功能的更多信息，请参阅以下ONTAP文档。



== 数据保护

了解更多关于ASA r2 系统支持的常见数据保护功能。



=== 集群外部密钥服务器

您可以配置与存储虚拟机上的集群外部密钥管理服务器的连接。使用集群密钥服务器，您可以在存储虚拟机上指定主密钥服务器和辅助密钥服务器。注册密钥时， ONTAP将首先尝试访问主密钥服务器，然后再依次尝试访问辅助服务器，直到操作成功完成，从而防止密钥重复。

link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-cluster-key-server-task.html["学习如何配置集群式外部密钥服务器"^]。



=== 静态加密的外部密钥管理

您可以使用一个或多个 KMIP 服务器来保护集群用于访问加密数据的密钥。

* link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-external-key-management-96-later-hw-task.html["启用外部密钥管理"^]。
* link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-external-key-management-96-later-nve-task.html["启用外部密钥管理 (NVE)"^] 。




== 数据安全性

了解更多关于ASA r2 系统支持的常见数据安全功能。



=== 管理员访问管理

分配给管理员的角色决定了管理员可以执行哪些功能。系统管理器为集群管理员和存储虚拟机管理员提供了预定义角色。您可以在创建管理员帐户时分配角色，也可以稍后分配其他角色。

* link:https://docs.netapp.com/us-en/ontap/task_security_administrator_access.html["学习如何使用系统管理器管理管理员访问权限"^]。




=== 客户端身份验证和授权

ONTAP使用标准方法来保护客户端和管理员对存储的访问，并防止病毒感染。先进技术可用于静态数据加密和 WORM 存储。  ONTAP通过与可信来源验证客户端计算机和用户的身份来验证其身份。  ONTAP通过将用户的凭据与文件或目录上配置的权限进行比较，来授权用户访问文件或目录。

link:https://docs.netapp.com/us-en/ontap/concepts/client-access-storage-concept.html["了解客户端身份验证和授权"^] 。



=== OAuth 2.0 身份验证

您可以使用开放授权（OAuth 2.0）框架来控制对ONTAP集群的访问。  OAuth 2.0 使用签名访问令牌来限制和控制对受保护资源的访问。

link:https://docs.netapp.com/us-en/ontap/authentication/overview-oauth2.html["了解 OAuth 2.0 身份验证"^] 。



=== SAML身份验证和管理员访问

您可以为 Web 服务配置和启用安全断言标记语言 (SAML) 身份验证。  SAML 通过外部身份提供商 (IdP) 而不是目录服务提供商（例如 Active Directory 和 LDAP）来验证用户身份。

link:https://docs.netapp.com/us-en/ontap/system-admin/configure-saml-authentication-task.html["学习配置 SAML 身份验证"^] 。



=== TLS 硬件卸载

您可以将整个集群的传输层安全性 (TLS) 加密和解密卸载到支持的以太网卡。这减少了 CPU 开销，并提高了使用 TLS 的系统的性能。

link:https://docs.netapp.com/us-en/ontap/networking/configure_tls_hardware_offload.html["了解如何配置 TLS 硬件卸载"^].



== 网络连接

了解更多关于ASA r2 系统支持的常见网络功能。



=== FIPS 合规性

ONTAP符合联邦信息处理标准 (FIPS) 140-2 的所有 SSL 连接要求。您可以打开和关闭 SSL FIPS 模式，全局设置 SSL 协议，并关闭ONTAP中的任何弱密码，例如 RC4。

从ONTAP 9.18.1 开始，SSL 支持后量子计算加密算法。这些算法可针对未来潜在的量子计算攻击提供额外保护，并且在 SSL FIPS 模式禁用时可用。

* link:https://docs.netapp.com/us-en/ontap/networking/configure_network_security_using_federal_information_processing_standards_fips.html["学习如何为所有 SSL 连接配置 FIPS"^]。




=== 链接聚合组（LAG）

接口组，也称为链路聚合组 (LAG)，是将同一节点上的两个或多个物理端口合并为一个逻辑端口而创建的。逻辑端口可提高弹性、可用性和负载分担能力。

link:https://docs.netapp.com/us-en/ontap/networking/combine_physical_ports_to_create_interface_groups.html["了解链接聚合组"^]。



== 性能

详细了解 ASA r2 系统支持的常见性能功能。



=== 修改控制自动 QoS 吞吐量上限增加的默认设置

自适应和非自适应 QoS 策略组会自动启用，以便在默认情况下将工作负载的吞吐量上限暂时提高 50%，持续时间为 1 秒，从而响应对更高性能的短期需求。从 ONTAP 9.19.1 开始，您可以修改这些默认设置。在 ONTAP 9.18.1 及更早版本中，这些设置无法更改。

link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["详细了解 QoS 吞吐量上限"^].



== SAN 配置

存储区域网络 (SAN) 由通过 iSCSI 或 FC 等 SAN 传输协议连接到主机的存储解决方案组成。您可以配置 SAN，以便存储解决方案通过一个或多个交换机连接到主机。如果使用 iSCSI，还可以配置 SAN，以便存储解决方案无需使用交换机即可直接连接到主机。



=== SAN 直接连接

从 ONTAP 9.19.1 开始，无需 FC 交换机即可在 FC 和 FC-NVMe 主机与 ONTAP 存储之间建立连接。主机可以直接连接到 ASA r2 系统上的 FC 适配器端口。在简单性至关重要的远程站点和混合环境中，直接连接功能尤其有价值。

* link:https://docs.netapp.com/us-en/ontap/san-config/configure-fc-nvme-hosts-ha-pairs-reference.html#direct-attach-fc-and-fc-nvme-configurations["详细了解 SAN 直接连接"^].




== SAN协议

ASA r2 系统支持所有 SAN 协议（iSCSI、FC、NVMe/FC、NVMe/TCP）。

* link:https://docs.netapp.com/us-en/ontap/san-admin/san-host-provisioning-concept.html["了解更多关于 iSCSI 协议的信息"^]。
* link:https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["了解更多关于光纤通道 (FC) 协议的信息"^]。
* link:https://docs.netapp.com/us-en/ontap/concept_nvme_provision_overview.html["了解 NVMe 协议"^]。
+
** link:https://docs.netapp.com/us-en/ontap/san-admin/nvme-copy-offload.html["学习如何配置 NVMe 复制卸载"^]。
+
从ONTAP 9.18.1 开始，支持 NVMe 复制卸载。 NVMe 复制卸载功能使 NVMe 主机能够将复制操作从其 CPU 卸载到ONTAP存储控制器的 CPU。主机可以将数据从一个 NVMe 命名空间复制到另一个 NVMe 命名空间，同时将其 CPU 资源保留给应用程序工作负载。

** link:https://docs.netapp.com/us-en/ontap/san-admin/enable-space-allocation.html["了解更多关于 NVMe 空间分配（取消映射）的信息"^]。
+
从ONTAP 9.16.1 开始，默认情况下为 NVMe 命名空间启用空间释放（也称为“打孔”和“取消映射”）。空间释放允许主机从命名空间中释放未使用的块以回收空间。







== 存储效率

存储效率是通过优化存储资源、最大限度地减少浪费的空间和减少写入数据的物理占用量来衡量存储系统有效利用可用空间的程度。

ONTAP 提供各种存储效率技术，可帮助您优化存储使用并降低成本。

link:https://docs.netapp.com/us-en/ontap/concepts/storage-efficiency-overview.html["详细了解 ONTAP 存储效率技术"].



=== 全局重复数据删除

从 ONTAP 9.19.1 开始，_全局重复数据删除_ 将 link:https://docs.netapp.com/us-en/ontap/concepts/deduplication-concept.html["现有 ONTAP 重复数据删除空间节省"^] 从存储单元级别扩展到整个存储可用区 (SAZ)。通过消除 SAZ 中所有存储单元中的重复数据块，可以显著提高存储效率并降低总拥有成本。全局重复数据删除不需要功能许可证，默认情况下处于启用状态，与现有存储效率技术无缝集成，以最小的性能影响透明运行，无需管理配置。



== System Manager

您可以在系统管理器中搜索各种操作、对象和信息主题。您还可以搜索表格数据中的特定条目。

link:https://docs.netapp.com/us-en/ontap/task_admin_search_filter_sort.html["学习如何在系统管理器中搜索、筛选和排序信息"^]。
