---
sidebar: sidebar 
permalink: learn-more/hardware-comparison.html 
keywords: compare asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, hardware comparison, asa r2 
summary: ASA系统提供针对纯SAN解决方案优化的硬件支持。ASA R2系统可优化硬件和软件。 
searchtitle: 将ASA R2系统与其他ONTAP系统进行比较 
---
= 将ASA R2系统与其他ONTAP系统进行比较
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA r2 系统为基于全闪存解决方案的纯 SAN 环境提供硬件和软件解决方案。r2 系统与其他ONTAP系统（ ASA 、 AFF和FAS）在ONTAP特性、存储层和支持协议的实现方面有所不同。

以下系统被归类为ASA r2 系统：

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30




== 性格差异

在ASA R2系统上、ONTAP软件经过简化、可为基本SAN功能提供支持、同时限制非SAN相关特性和功能的可见性和可用性。例如、在ASA R2系统上运行的System Manager不会显示为NAS客户端创建主目录的选项。此简化版本的ONTAP标识为_ ASA R2特性_。在ASA系统上运行的ONTAP标识为_ ASA ONTAP特性_。在AFF和FAS ONTAP系统上运行的ONTAP标识为_UNITALITY ONTAP _。ONTAP命令参考(手册页)、REST API规范和EMS消息(如果适用)中引用了ONTAP个性化设置之间的差异。

您可以从System Manager或ONTAP命令行界面验证ONTAP存储的特性。

* 从System Manager菜单中，选择*Cluster > Overview*。
* 从 CLI 输入： `system node show -personality -is-disaggregated`


对于ASA r2 系统，_personality_ 为 _ASA r2_，且 _is-disaggregated_ 的状态为 _true_。

ONTAP存储系统的特性无法更改。



== 存储层差异

ASA r2 系统使用简化的存储层，该存储层与FAS、 AFF和ASA系统使用的存储层不同。

.FAS、 AFF和ASA系统
FAS、 AFF和ASA系统的存储层使用聚合作为基本存储单元。聚合拥有存储系统中可用的一组特定磁盘。聚合将其拥有的磁盘上的空间分配给 LUN 和命名空间的卷。使用这些系统， ONTAP用户可以创建和修改聚合、卷、LUN 和命名空间。

.ASA r2系统
ASA r2 系统中的存储层使用存储可用区，而非聚合。存储可用区是单个 HA 对的两个节点均可访问的公共存储池。HA对中的两个节点均可访问其共享存储可用区中的所有可用磁盘。例如，在双节点ASA r2 系统ONTAP集群中，有一个存储可用区，集群中的两个节点均可访问。在四节点ASA r2 系统ONTAP集群中，有两个存储可用区。集群中的每个 HA 对都可以访问其中一个存储可用区。

创建存储单元（基于 LUN 或 NVMe 命名空间）时， ONTAP会自动在相应的存储可用区中创建一个卷来容纳该存储单元。新创建的卷将自动放置在该存储可用区内，以实现最佳性能和均衡的容量利用率。存储可用区内的容量利用率会根据您的ONTAP版本进行平衡。link:administer/space-balancing.html["了解ASA r2 集群中的容量均衡"^]。



== ASA r2 系统差异概述

ASA r2 系统与FAS、 AFF和ASA系统有以下不同之处：

[cols="1h,2,2,2,2"]
|===
|  | ASA r2 | ASA | AFF | FAS 


 a| 
* ONTAP个性化*
| ASA r2 | ASA | 统一 | 统一 


 a| 
*SAN协议支持*
| 是 | 是 | 是 | 是 


 a| 
*NAS协议支持*
| 否 | 否 | 是 | 是 


 a| 
*存储层支持*
| 存储可用性区域 | 聚合 | 聚合 | 聚合 
|===
由于这种自动化且简化的存储管理方法，某些 System Manager 选项、 ONTAP命令和 REST API 端点在ASA r2 系统上不可用或使用受限。例如，由于ASA r2 系统的卷创建和管理是自动化的，因此“卷”菜单不会显示在 System Manager 中，并且 `volume create`命令不受支持。link:cli-support.html["了解有关不受支持的ASA r2 命令的更多信息"] 。

下面介绍了ASA R2系统与ONTAP、AFF和ASA系统之间与FAS命令行界面(CLI)和REST API相关的主要区别。

.使用协议服务创建默认存储虚拟机
新集群会自动包含一个默认数据存储虚拟机 (VM)，并启用 SAN 协议。  IP 数据 LIF 支持 iSCSI 和 NVMe/TCP 协议，并使用 `default-data-blocks`默认服务策略。

.自动创建卷
创建存储单元(LUN或命名空间)会自动从存储可用性区域创建卷。这样便可简化并使用通用命名空间。删除存储单元会自动删除关联的卷。

.对精简配置和厚配置进行的更改
存储单元始终在ASA R2存储系统上进行精简配置。不支持厚配置。

.对数据压缩进行的更改
ASA R2系统不会应用对温度敏感的存储效率。在ASA R2系统上、数据压缩不基于_hot_(经常访问)数据或_col_(不经常访问)数据。数据压缩开始时无需等待数据变冷。

.了解更多信息
* 详细了解 link:https://docs.netapp.com/us-en/ontap-systems-family/intro-family.html["ONTAP硬件系统"^]。
* 请参见中的ASA和ASA R2系统的完整配置支持和限制link:https://hwu.netapp.com/["NetApp Hardware Universe"^]。
* 了解有关的更多信息link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"^]。

