---
sidebar: sidebar 
permalink: learn-more/software-support-limitations.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa, a50, asa a30, asa a20, asa c30, unsupported features 
summary: 虽然ASA R2系统为SAN解决方案提供了广泛的支持、但某些ONTAP软件功能不受支持。 
---
= ASA R2存储系统的ONTAP软件支持和限制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
虽然ASA R2系统为SAN解决方案提供了广泛的支持、但某些ONTAP软件功能不受支持。

.ASA R2系统不支持以下功能：
* FabricPool
* LUN厚配置
* MetroCluster
* NetApp 聚合加密（NAE）
* 对象协议
* ONTAP S3 SnapMirror和S3 API
* SnapLock
+
SnapLock Compliance 和 Enterprise 模式在 SAN 环境中的主集群上不受支持。SnapLock for SnapVault 在辅助集群上受支持。

* SnapMirror复制在ASA r2 系统上受支持，但存在以下限制：
+
** 不支持SnapMirror同步复制。
** SnapMirror异步复制仅支持在两个ASA r2系统之间进行。SnapMirror异步复制不支持在ASA r2 系统与ASA、 AFF或FAS系统或云之间进行。
+
详细了解link:../data-protection/pre-defined-protection-policies.html["ASA r2 系统支持SnapMirror复制策略"]。

** SnapMirror主动同步仅支持在两个ASA r2 系统之间进行。
+
详细了解link:../data-protection/snapmirror-active-sync.html["ASA r2 系统上的SnapMirror主动同步"]。





.ASA R2系统支持以下功能：
* 双层加密
+
ASA r2 系统支持使用自加密驱动器 (SED) 的硬件加密和使用 NetApp 卷加密 (NVE) 技术的软件加密。link:../secure-data/encrypt-data-at-rest.html["了解如何应用双层加密"]保护 ASA r2 系统上的数据。



.了解更多信息
* link:https://hwu.netapp.com/["NetApp Hardware Universe"^]有关ASA R2硬件支持和限制的详细信息、请参见。

