---
sidebar: sidebar 
permalink: administer/space-balancing.html 
keywords: capacity, space, rebalancing, balanced, placement, balance, asa r2 
summary: 您可能需要重命名节点、以符合组织的命名约定或出于其他管理原因。 
---
= 了解ASA r2 集群中的ONTAP容量均衡
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
对于ASA r2 系统， ONTAP使用 _均衡放置_ 将新创建的存储单元自动放置在最佳存储可用区，以实现最佳性能和均衡的存储利用率。如果您运行的是ONTAP 9.17.1 或更高版本，则现有存储单元占用的空间将使用_动态空间平衡_进行平衡。如果您正在运行ONTAP 9.16.1，则现有存储单元占用的空间将使用基于副本的工作负载重新平衡进行平衡。

[cols="2"]
|===
| 功能 | 得到支持…… 


| 均衡布局 | ONTAP 9.16.1 及更高版本 


| 动态空间平衡 | ONTAP 9.17.1 及更高版本 


| 基于副本的工作负载重新平衡 | 仅限ONTAP 9.16.1 
|===
.均衡布局
通过_均衡放置_，新创建的存储单元会自动放置在最佳存储可用区内，以实现最佳性能和均衡的存储利用率。  ONTAP 9.16.1 及更高版本默认启用均衡放置。

.动态空间平衡
通过动态空间平衡， ONTAP会主动监控集群中的可用空间，并自动在存储可用区内移动存储单元，以保持空间利用率的平衡。如果集群范围内的容量利用率达到 80%，则会自动发出 EMS 警告；如果达到 90%，则会自动发出 EMS 警报。

升级到ONTAP 9.17.1 或更高版本后 14 天，动态空间平衡功能将默认启用。如果您需要修改默认的 14 天启用期，请联系NetApp支持。启用动态空间平衡后，无法从ONTAP 9.17.1 回滚。

动态空间平衡根据集群中所有节点可用空间的总体平均值（全局平均值）以_正常模式_或_低空间模式_运行。

* *普通模式*
+
在正常模式下， ONTAP每三分钟检查一次，以确定是否需要动态空间平衡。当满足以下条件时，动态空间平衡功能以正常模式运行：

+
** 全球平均空隙率为 10% 或更高。
** 集群中至少有一个节点的可用空间比全局平均水平要多。
** 集群中至少有一个节点的可用空间比全局平均水平少 20%。


* *低空间模式*
+
在低空间模式下， ONTAP每分钟检查一次，以确定是否需要动态空间平衡。当满足以下条件时，动态空间均衡以低空间模式运行：

+
** 全球平均自由空间不足10%。
** 集群中至少有一个节点的可用空间比全局平均水平要多。
** 集群中至少有一个节点的可用空间少于全局平均水平。




.基于副本的工作负载重新平衡
通过基于复制的工作负载重新平衡，如果存储可用区内出现存储利用率不平衡的情况， ONTAP会自动将造成不平衡的存储单元复制到具有更大可用空间的存储可用区。如果目标存储可用区没有足够的可用空间， ONTAP将不会执行任何平衡操作。基于副本的工作负载重新平衡仅适用于运行ONTAP 9.16.1 的ASA r2 系统，并且默认情况下在这些系统上启用。在ONTAP 9.17.1 及更高版本中，它被动态空间平衡所取代。

如果您需要修改基于副本的工作负载重新平衡的默认设置，请联系NetApp支持。
