---
sidebar: sidebar 
permalink: data-protection/manage-consistency-groups.html 
keywords: consistency groups, snapshots, data protection, protect data, add, remove, delete, storage units, lun, namespace, increase capacity 
summary: 使用一致性组可同时对多个存储单元执行各种操作、而不是对每个单元单独执行操作。 
---
= 了解ASA r2 存储系统上的ONTAP一致性组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
一致性组是作为单个单元进行管理的存储单元的集合。使用一致性组简化存储管理。

例如，假设您有一个由一致性组中的 10 个存储单元组成的数据库，并且您需要备份整个数据库。您无需备份每个存储单元，只需向一致性组添加快照数据保护即可备份整个数据库。将存储单元作为一致性组而不是单独备份也可以提供所有单元的一致备份，而单独备份单元可能会造成不一致。

从ONTAP 9.16.1 开始，您可以使用系统管理器在ASA r2 系统上创建分层一致性组。在层次结构中，一个或多个一致性组被配置为父一致性组下的子组。

通过分层一致性组、您可以将单个快照策略应用于每个子一致性组、并通过复制父一致性组将所有子一致性组的快照作为一个单元复制到远程集群。这样可以简化复杂数据结构的数据保护和管理。例如、假设您创建了一个名为的父一致性组 `SVM1_app`、其中包含两个子一致性组： `SVM1app_data`用于应用程序数据和 `SVM1app_logs`应用程序日志。的快照每15分钟创建一次、的 `SVM1app_logs`快照 `SVM1app_data`每小时创建一次。父一致性组 `SVM1_app,`具有一个SnapMirror策略、该策略每24小时将和 `SVM1app_logs`的快照复制 `SVM1app_data`到远程集群。父一致性组 `SVM1_app`作为一个单元进行管理、子一致性组作为单独的单元进行管理。



== 复制关系中的一致性组

从ONTAP 9.17.1 开始，您可以对异步复制关系或SnapMirror活动同步关系中的一致性组进行以下几何更改，而无需破坏或删除该关系。当主一致性组上发生几何变化时，该变化将被复制到辅助一致性组。

* link:manage-consistency-groups-add-remove-storage-units.html["修改存储单元的大小"]通过添加或删除存储单元。
* link:manage-hierarchical-consistency-groups.html#promote-an-existing-consistency-group-into-a-parent-consistency-group["提升单个一致性组"]到父一致性组。
* link:manage-hierarchical-consistency-groups.html#demote-a-parent-consistency-group-to-a-single-consistency-group["降级父一致性组"]到单个一致性组。
* link:manage-hierarchical-consistency-groups.html#detach-a-child-consistency-group-from-a-parent-consistency-group["分离子一致性组"]来自父一致性组。
* link:manage-hierarchical-consistency-groups.html#create-a-child-consistency-group["创建子一致性组"]使用现有的一致性组。


在ONTAP 9.16.1 中，您必须link:snapmirror-active-sync-break-relationship.html["打破异步复制关系"]和link:snapmirror-active-sync-delete-relationship.html["删除SnapMirror活动同步关系"]在对一致性组进行几何更改之前。
